const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {generationNoticeRuntime}=require('../out/view/generationNotice');
// AI_NOTE: 非同期通知の消去・失敗・読取/再試行の分離を仮想時計で検証し、実画面確認は独立fixtureへ分ける。
function setup(layers){
 const nodes=[],timers=new Map(),events={},requests=[],arrivals=[];let timerId=0;
 class Element{
  constructor(tag){this.tagName=tag;this.children=[];this.style={};this.dataset={};this.hidden=false;this.textContent='';this.classList={add(){},contains:()=>false};nodes.push(this)}
  setAttribute(k,v){this[k]=v} append(...ns){ns.forEach(n=>{n.parent=this;this.children.push(n)})}before(n){this.parent.append(n)}remove(){this.parent.children=this.parent.children.filter(n=>n!==this)}
  focus(){doc.activeElement=this}getBoundingClientRect(){return {width:460,height:682,right:1280}}click(){this.onclick?.()}
 }
 const doc={hidden:false,activeElement:null,createElement:t=>new Element(t),getElementById:id=>nodes.find(n=>n.id===id),addEventListener:(k,v)=>events[k]=v};doc.body=new Element('body');
 const header=new Element('header');doc.body.append(header);for(const id of ['toggle-sidebar','source','sidebar','workspace']){const n=new Element('div');n.id=id;header.append(n)}
 const c={document:doc,window:{addEventListener:(k,v)=>events[k]=v,removeEventListener(){}},innerWidth:1280,MutationObserver:class{observe(){}disconnect(){}},getComputedStyle:()=>({display:'flex'}),viewId:'test',initial:{sourceSha256:'a',layers},onState:n=>arrivals.push(n),setTimeout:(f,ms)=>{const id=++timerId;timers.set(id,{f,ms});return id},clearTimeout:id=>timers.delete(id),fetch:async(url,init)=>{requests.push({url,init});return {ok:true,json:async()=>({layers:{inline:{status:'ready'}}})}}};
 const api=vm.runInNewContext(generationNoticeRuntime+';installGenerationNotice({initial,onState})',c);return{api,c,n:id=>doc.getElementById(id),timers,requests,arrivals,events,fire:async ms=>{const found=[...timers].find(([,t])=>t.ms===ms);assert.ok(found,'timer '+ms);timers.delete(found[0]);await found[1].f()}};
}
const layer=status=>({status,completed:status==='ready'?1:0,total:1});
test('cached ready/stale/empty shows no notification and performs no polling',()=>{for(const layers of [{},{inline:layer('ready')},{background:layer('stale'),inline:layer('stale')}]){const s=setup(layers);assert.equal(s.n('generation-notice').hidden,true);assert.equal(s.n('generation-chip').hidden,true);assert.equal(s.timers.size,0)}});
test('pending uses item labels; collapse survives arrivals; success disappears after three seconds',async()=>{const s=setup({background:layer('ready'),inline:layer('generating')});assert.equal(s.n('generation-notice').hidden,false);s.n('generation-fold').onclick();assert.equal(s.n('generation-chip').hidden,false);s.api.accept({layers:{background:layer('ready'),inline:layer('ready')}});assert.equal(s.n('generation-chip').textContent,'生成完了');await s.fire(3000);assert.equal(s.n('generation-chip').hidden,true);assert.equal(s.n('generation-notice').hidden,true)});
test('failure remains until closed; only selected failed item is retried',async()=>{const s=setup({background:layer('ready'),inline:layer('error')});assert.equal(s.n('generation-retry-inline').hidden,false);assert.equal(s.n('generation-retry-background').hidden,true);assert.ok(![...s.timers.values()].some(t=>t.ms===3000));await s.n('generation-retry-inline').onclick();assert.deepEqual(JSON.parse(s.requests[0].init.body),{layer:'inline'});assert.ok(s.requests[0].url.endsWith('/retry'));assert.equal(s.c.document.activeElement.id,'source')});
test('dismissed same failure stays hidden and new failure reappears',()=>{const s=setup({inline:layer('error')});s.n('generation-close').onclick();s.api.accept({layers:{inline:layer('error')}});assert.equal(s.n('generation-notice').hidden,true);s.api.accept({layers:{inline:layer('ready'),diagram:layer('error')}});assert.equal(s.n('generation-notice').hidden,false)});
test('connection recovery reads state only; source mismatch never applies changed content',async()=>{const s=setup({inline:layer('generating')});s.c.fetch=async()=>{throw Error('Failed to fetch')};await s.fire(500);assert.equal(s.n('generation-reconnect').hidden,false);s.c.fetch=async(url,init)=>{s.requests.push({url,init});return{ok:true,json:async()=>({layers:{inline:layer('ready')}})}};await s.n('generation-reconnect').onclick();assert.equal(s.requests[0].init,undefined);assert.ok(s.requests[0].url.endsWith('/state'));const count=s.arrivals.length;s.api.accept({sourceSha256:'b'});assert.equal(s.arrivals.length,count);assert.equal(s.n('generation-retry-inline').hidden,true)});
test('no retry affordance for unretryable layer; hidden and disposed pages stop polls',()=>{const s=setup({diagram:{...layer('error'),retryable:false},inline:layer('generating')});assert.equal(s.n('generation-retry-diagram').hidden,true);s.c.document.hidden=true;s.events.visibilitychange();assert.equal(s.timers.size,0);s.events.pagehide();assert.equal(s.timers.size,0)});
