import type { AgentShowResult } from "./projectDiagramBridge";
import { buildProjectDiagramHtml, projectFlowchartCss, projectFlowchartRuntime } from "./projectDiagram";
import { sharedCodeSurfaceCss, sharedCodeSurfaceRuntime } from "./sharedCodeSurface";
import { semanticBackgroundRuntime } from "./semanticBackground";
import { generationNoticeCss, generationNoticeRuntime } from "./generationNotice";
import { inlineNameLayerRuntime } from "./inlineNameLayer";
import { loopRowControlsCss, loopRowControlsRuntime } from "./loopRowControls";

export type CombinedWebViewData = {
    file?: string;
    standard?: AgentShowResult["standard"];
    diagram?: AgentShowResult["diagram"];
    diagramHtml?: string;
    annotations?: AgentShowResult["annotations"];
    trace?: AgentShowResult["trace"];
    sourceSha256?: string;
    revision?: number;
    sourceChanged?: boolean;
    layers?: AgentShowResult["layers"];
};

function safeJson(value: unknown): string {
    return JSON.stringify(value).replace(/[<>&\u2028\u2029]/g, (character) =>
        `\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`);
}

// AI_NOTE: 4機能を別々のコード複製へ分けず、標準色・トレース値・名称辞書を一つの行DOMへ合成する。
// 右ペインだけを標準カードとコード図で切り替えるため、本文の選択・スクロール位置は切替時も維持される。
// AI_NOTE: コードと実行値は別々に横スクロールし、縦位置だけ同期する。長い値がコード行高を変えない。
export function buildCombinedWebView(data: CombinedWebViewData, viewId: string): string {
    const diagramHtml = data.diagram
        ? buildProjectDiagramHtml(data.diagram, undefined, undefined, { selectableNodes: true })
        : "";
    const initial = safeJson(data);
    const encodedViewId = safeJson(viewId);
    return `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>AI Code Guide</title>
  <style>
    :root{color-scheme:dark;--page:#181818;--side:#202020;--code:#161616;--text:#d4d4d4;--muted:#969696;--border:#3a3a3a;--focus:#4fc1ff;--trace:#9cdcfe;--keyword:#c586c0;--function:#dcdcaa;--string:#ce9178;--number:#b5cea8;--comment:#6a9955;--name:#9cdcfe;--type:#4ec9b0;--decorator:#dcdcaa;--editor-font:Consolas,"Courier New",monospace;--editor-font-size:13px;--line-height:21px}
    *{box-sizing:border-box}html,body{height:100%;margin:0}body{overflow:hidden;color:var(--text);background:var(--page);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input{font:inherit}.page{height:100%;display:flex;flex-direction:column}.header{flex:none;display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:38px;padding:5px 8px 5px 13px;border-bottom:1px solid var(--border);background:#1d1d1d}.heading{min-width:0;flex:1 1 auto}.title{margin:0;font-size:13px;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.header-tools{min-width:0;display:flex;align-items:center;gap:8px}.header.sidebar-hidden .tabs{display:none}.header-button,.tab,.toolbar-button,.expand-button,.ask-button{border:1px solid #505050;border-radius:5px;color:var(--text);background:#2c2c2c;cursor:pointer}.header-button{padding:5px 9px;font-size:10px}.header-button:hover,.header-button:focus-visible,.tab:hover,.tab:focus-visible,.toolbar-button:hover,.toolbar-button:focus-visible,.expand-button:hover,.expand-button:focus-visible,.ask-button:hover,.ask-button:focus-visible{border-color:var(--focus);outline:none}.workspace{min-height:0;flex:1;display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,36%)}.workspace.sidebar-hidden{grid-template-columns:minmax(0,1fr)}.workspace.sidebar-hidden .sidebar{display:none}.source{min-width:0;min-height:0;overflow:hidden;background:var(--code)}.header #toggle-sidebar{margin-left:auto;flex:none;white-space:nowrap}.toolbar-button{padding:3px 7px;font-size:10px}.toolbar-button:disabled{opacity:.35;cursor:default}.source-lines{width:100%;height:100%}.source-pane{min-width:0;min-height:0;overflow:auto;scrollbar-gutter:stable}.source-code-pane,.source-trace-pane{width:100%;height:100%}.source-pane-rows{width:100%;min-width:max-content;padding:3px 0 18px}.source-row{position:relative;width:100%;min-width:max-content;height:var(--line-height);border-left:3px solid transparent;font:var(--editor-font-size)/var(--line-height) var(--editor-font)}.source-code-row{display:grid;grid-template-columns:48px max-content}.source-trace-row{display:block}.source-row.in-unit{border-left-color:var(--unit-color);background:color-mix(in srgb,var(--unit-color) 12%,transparent)}.source-row.selected{box-shadow:inset 2px 0 var(--selection-color)}.line-no{padding-right:11px;color:#707070;text-align:right;user-select:none}.code-cell{position:relative;min-width:max-content;padding-right:18px;white-space:pre;user-select:text;cursor:text}.trace-note{display:block;min-width:max-content;height:var(--line-height);padding:0 12px;color:var(--muted);white-space:pre}.trace-note.has-value{color:var(--trace)}.symbol-anchor{display:inline;color:inherit;text-decoration:none;background:none;outline:none;cursor:pointer}.symbol-anchor:focus-visible{outline:1px solid var(--focus);outline-offset:1px}.empty{grid-column:1/-1;padding:28px;color:var(--muted);text-align:center}
    ${sharedCodeSurfaceCss}
    ${generationNoticeCss}
    ${loopRowControlsCss}
    .sidebar{min-width:0;min-height:0;display:flex;flex-direction:column;border-left:1px solid var(--border);background:var(--side)}.tabs{display:flex;gap:4px;min-width:0;overflow-x:auto}.tab{flex:none;padding:5px 9px;color:var(--muted);font-size:10px;white-space:nowrap}.tab.active{border-color:var(--focus);color:var(--text);background:#173247}.panel{display:none;min-height:0;flex:1;overflow:auto;padding:8px}.panel.active{display:block}.trace-panel{padding:0;overflow:hidden}.trace-panel.active{display:flex}.cards{display:flex;flex-direction:column;gap:4px}.card,.group-title{--accent:#9d9d9d;display:flex;align-items:center;gap:6px;min-height:34px;padding:6px 7px;border:0;border-left:3px solid var(--accent);border-radius:4px;color:var(--text);background:color-mix(in srgb,var(--accent) 15%,transparent);cursor:pointer}.card:hover,.group-title:hover{filter:brightness(1.1)}.card.active,.group-title.active{outline:2px solid var(--focus);outline-offset:-2px}.card.child{margin-left:13px;background:color-mix(in srgb,var(--accent) 9%,transparent)}.kind{flex:0 0 34px;color:var(--muted);font-size:9px}.label{min-width:0;flex:1;overflow-wrap:anywhere;font:600 11px/1.35 var(--editor-font);user-select:text;cursor:text}.expand-button{flex:none;padding:4px 7px;border:0;background:transparent;font-size:10px}.expansion{margin:-4px 0 4px;padding:8px 9px;border-left:3px solid var(--accent);background:color-mix(in srgb,var(--accent) 10%,transparent);font-size:11px;line-height:1.45}.expansion-row+.expansion-row{margin-top:6px}.expansion-key{color:var(--accent);font-size:9px;font-weight:700}.block{margin-top:6px;padding-top:5px;border-top:1px solid color-mix(in srgb,var(--accent) 35%,transparent)}.block-lines{float:right;color:var(--muted);font:9px/1.4 var(--editor-font)}
    .diagram-panel{padding:10px}.diagram-summary{margin:0 0 8px;padding:9px 10px;border-left:3px solid #d7ba7d;background:#28251a;font-size:11px;line-height:1.45}.pd-layout{width:100%;display:flex;flex-direction:column;--pd-line:#d7ba7d}.pd-node{position:relative;z-index:1;width:100%;min-width:0;border:0;color:var(--text);background:transparent;font:inherit;text-align:left}.pd-node.selectable{cursor:text;user-select:text}.pd-node:hover{background:#ffffff0b}.pd-node[aria-current="true"]{outline:2px solid var(--focus);outline-offset:-2px}.pd-node-heading{display:flex;align-items:center;gap:6px}.pd-node-label{font-size:12px;font-weight:650}.pd-node-symbol,.pd-node-description,.pd-emphasis-reason{color:var(--muted);font-size:10px;overflow-wrap:anywhere}.pd-node-jump,.pd-detail-jump{display:inline-flex;padding:4px 6px;border:1px solid #555;border-radius:4px;color:var(--focus);background:#252525;font-size:9px;cursor:pointer}.pd-edge-label{display:inline-block;padding:3px 7px;color:#f1d995;background:#39331f;font-size:10px;font-weight:700}.pd-flow-node,.pd-reading-node,.pd-dependency-node{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:8px;padding:8px;border-left:2px solid var(--pd-accent,#d7ba7d);border-bottom:1px solid #3a3a3a}.pd-flow-link{height:18px;border-left:1px solid #d7ba7d;margin-left:8px}.pd-flow-branches{display:flex;flex-direction:column;gap:5px;margin:4px 0 4px 10px;padding-left:11px;border-left:1px solid #d7ba7d}.pd-flow-branch,.pd-dependency-child{display:flex;flex-direction:column;gap:3px}.pd-reading-row{display:grid;grid-template-columns:28px minmax(0,1fr);gap:6px;padding:3px 0}.pd-reading-number{display:flex;width:25px;height:25px;align-items:center;justify-content:center;border-radius:50%;color:#1e1e1e;background:#d7ba7d;font-size:10px}.pd-dependency-children{margin-left:12px;padding-left:10px;border-left:1px solid #d7ba7d}.pd-reference-mark{color:#d7ba7d}.pd-node.reference{opacity:.75}
    ${projectFlowchartCss}
    .symbol-card{position:fixed;z-index:100;width:min(430px,calc(100vw - 16px));max-height:min(560px,calc(100vh - 16px));overflow:auto;padding:12px;border:1px solid #505050;border-radius:7px;color:#d4d4d4;background:#252526;box-shadow:0 8px 28px #0009;font:13px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.symbol-card[hidden]{display:none}.symbol-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.symbol-card h2{margin:0;font-size:14px}.symbol-kind{margin:2px 0 0;color:#999;font-size:10px}.symbol-description{margin:10px 0}.chat{display:grid;gap:7px;margin-top:10px;padding-top:9px;border-top:1px solid #454545}.chat-log{display:grid;gap:5px;max-height:180px;overflow:auto}.message{margin:0;padding:6px 8px;border-radius:5px;white-space:pre-wrap}.message.user{margin-left:28px;background:#26354d}.message.assistant{margin-right:15px;background:#333}.ask-row{display:grid;grid-template-columns:1fr auto;gap:6px}.ask-row input{min-width:0;padding:7px;border:1px solid #555;border-radius:5px;color:#eee;background:#1e1e1e}.ask-button{padding:6px 8px;font-size:11px}.status{position:fixed;z-index:110;right:12px;bottom:10px;max-width:520px;padding:6px 9px;border:1px solid var(--border);border-radius:5px;color:var(--focus);background:#292929;font-size:10px}.status:empty{display:none}.status.error{color:#f48771}
    @media(max-width:760px){.workspace{grid-template-columns:minmax(0,1fr) minmax(260px,42%)}.source-code-row{grid-template-columns:43px max-content}.pd-flow-node,.pd-reading-node,.pd-dependency-node{grid-template-columns:minmax(0,1fr)}}
  </style>
</head>
<body>
  <main class="page">
    <header class="header" id="header"><div class="heading"><h1 class="title" id="title"></h1></div><div class="header-tools"><div class="tabs" id="tabs"></div><button class="header-button" id="toggle-sidebar" type="button">サイドバーをしまう</button></div></header>
    <section class="workspace" id="workspace"><section class="source" id="source" tabindex="-1"><div class="source-lines" id="source-lines"></div></section><aside class="sidebar" id="sidebar"><section class="panel trace-panel" id="trace-panel" aria-label="実行トレース"></section><section class="panel" id="standard-panel" aria-label="標準ビュー"><div class="cards" id="cards"></div></section><section class="panel diagram-panel" id="diagram-panel" aria-label="コード図"><p class="diagram-summary" id="diagram-summary"></p>${diagramHtml}</section></aside></section>
    <p class="status" id="status" role="status"></p>
  </main>
  <script>
    const data=${initial};const viewId=${encodedViewId};let standard=data.standard||{source:[],items:[]};let annotations=(data.annotations?.items||[]).filter(item=>item.kind==="symbol"&&item.symbolKey);const conversations=data.annotations?.conversations||{};let traceFunctions=data.trace?.functions||[];let selectedId="";let activeTab=data.trace?"trace":data.standard?"standard":"diagram";let pinnedKey=null;let activeAnchor=null;let hoverTimer=null;
    const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=String(text);return node};const setStatus=(text,error=false)=>{const node=document.getElementById("status");node.textContent=text;node.classList.toggle("error",error)};
    ${sharedCodeSurfaceRuntime}
    ${semanticBackgroundRuntime}
    ${generationNoticeRuntime}
    ${inlineNameLayerRuntime}
    ${loopRowControlsRuntime}
    const loopRows=installLoopRowControls({functions:()=>traceFunctions,afterChange:()=>applySource()});
    ${projectFlowchartRuntime}
    const itemById=id=>(standard.items||[]).find(item=>item.id===id)||null;const itemColor=item=>item?.color||({class:"#c586c0",constant:"#dcdcaa",function:"#4ec9b0"}[item?.kind]||"#9d9d9d");const kindLabel=item=>item.kind==="class"?"クラス":item.kind==="constant"?"定数":item.parent?"メソッド":"関数";const blockColors=["#4ec9b0","#d7ba7d","#c586c0","#569cd6","#ce9178","#b5cea8"];
    // AI_NOTE: 未生成部分を定義全体色で代用せず、検証済みLLM範囲だけindexから描画する。
    const unitForLine=line=>semanticIndex.get(line)||null;
    const sourceLines=()=>{if(standard.source?.length)return standard.source;const context=data.annotations?.context;if(context?.code?.length)return context.code;const traced=traceFunctions.flatMap(fn=>fn.code||[]);return[...new Map(traced.map(row=>[row.line,row])).values()].sort((a,b)=>a.line-b.line)};
    const appendPython=(parent,text,beforeContext="",afterContext="")=>codeSurface.appendPython(parent,text,beforeContext,afterContext);const annotatedPython=text=>{const root=el("code","code");const symbols=annotations.filter(item=>item.startLine===Number(root.dataset.line));return root};
    const itemFor=key=>annotations.find(item=>item.symbolKey===key);const kindName=kind=>({variable:"変数",function:"関数",method:"メソッド",class:"クラス"}[kind]||"名称");const card=el("aside","symbol-card");card.hidden=true;document.body.append(card);const cancelHide=()=>{if(hoverTimer!==null){clearTimeout(hoverTimer);hoverTimer=null}};const hideCard=()=>{cancelHide();if(pinnedKey)return;card.hidden=true;card.replaceChildren();activeAnchor=null};const scheduleHide=()=>{cancelHide();hoverTimer=setTimeout(hideCard,180)};const positionCard=anchor=>{const bounds=card.getBoundingClientRect(),target=anchor.getBoundingClientRect();card.style.left=Math.max(8,Math.min(innerWidth-bounds.width-8,target.left))+"px";const above=target.top-bounds.height-8;card.style.top=(above>=8?above:Math.min(innerHeight-bounds.height-8,target.bottom+8))+"px"};
    const updateExplanation=(key,explanation)=>annotations.filter(item=>item.symbolKey===key).forEach(item=>item.explanation=explanation);const ask=async(key,input,button,mode="ask")=>{button.disabled=true;setStatus(mode==="undo"?"前の説明へ戻しています…":"回答を作っています…");try{const response=await fetch("/view/"+viewId+"/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbolKey:key,question:input.value,mode})});if(!response.ok)throw new Error(await response.text());const result=await response.json();conversations[key]=result.history||[];updateExplanation(key,result.explanation);showSymbol(activeAnchor,itemFor(key),true,result.canUndo);setStatus(mode==="undo"?"前の説明へ戻しました。":"説明を更新しました。")}catch(error){setStatus(error?.message||"説明を更新できませんでした。",true)}finally{button.disabled=false}};
    const showSymbol=(anchor,item,pinned=false,canUndo=false)=>{if(!anchor||!item||(!pinned&&getSelection()?.toString()))return;cancelHide();activeAnchor=anchor;card.replaceChildren();const head=el("div","symbol-card-head"),names=el("div","");names.append(el("h2","",item.label),el("p","symbol-kind",kindName(item.symbolKind)));const action=el("button","ask-button",pinned?"閉じる":"質問する");action.type="button";action.onclick=()=>{if(pinned){pinnedKey=null;card.hidden=true}else{pinnedKey=item.symbolKey;showSymbol(anchor,item,true,(conversations[item.symbolKey]||[]).length>0)}};head.append(names,action);card.append(head,el("p","symbol-description",item.explanation));if(pinned){const chat=el("div","chat"),log=el("div","chat-log");(conversations[item.symbolKey]||[]).forEach(message=>log.append(el("p","message "+message.role,message.content)));if(log.childNodes.length)chat.append(log);const form=el("form","ask-row"),input=el("input",""),send=el("button","ask-button","質問する");input.maxLength=1000;input.placeholder="この名前について質問";form.append(input,send);form.onsubmit=event=>{event.preventDefault();if(input.value.trim())ask(item.symbolKey,input,send)};chat.append(form);if(canUndo){const undo=el("button","ask-button","前の説明に戻す");undo.type="button";undo.onclick=()=>ask(item.symbolKey,input,undo,"undo");chat.append(undo)}card.append(chat)}card.hidden=false;requestAnimationFrame(()=>positionCard(anchor))};
    const codeWithSymbols=(text,line)=>{const root=el("code","code");let cursor=0;const entries=annotations.filter(item=>item.startLine===line).map(item=>({item,start:Math.max(0,Math.min(text.length,item.startCol??0)),end:Math.max(1,Math.min(text.length,item.endCol??((item.startCol??0)+1)))})).sort((a,b)=>a.start-b.start||a.end-b.end);entries.forEach(({item,start,end})=>{if(start<cursor)return;appendPython(root,text.slice(cursor,start),text.slice(0,cursor),text.slice(start));const anchor=el("span","symbol-anchor");anchor.tabIndex=0;anchor.dataset.symbolKey=item.symbolKey;anchor.setAttribute("aria-label",item.label+"。"+item.explanation);appendPython(anchor,text.slice(start,end),text.slice(0,start),text.slice(end));anchor.onmouseenter=()=>{if(!pinnedKey)showSymbol(anchor,item)};anchor.onmouseleave=scheduleHide;anchor.onfocus=()=>{if(!pinnedKey)showSymbol(anchor,item)};anchor.onblur=scheduleHide;anchor.onclick=event=>{if(event.detail===1&&!getSelection()?.toString()){pinnedKey=item.symbolKey;showSymbol(anchor,item,true,(conversations[item.symbolKey]||[]).length>0)}};root.append(anchor);cursor=end});appendPython(root,text.slice(cursor),text.slice(0,cursor),"");return root};
    const applyRowState=(row,base,line,unit,inside,active)=>{row.className="source-row "+base+(unit?" in-unit":"")+(inside&&unit&&active.kind!=="class"?" selected":"");row.style.setProperty("--unit-color",unit?.color||"transparent");row.style.setProperty("--selection-color",itemColor(active))};
    const applySource=()=>{loopRows.refresh();updateSemanticIndex(standard);const active=itemById(selectedId),traceArea=document.getElementById("source-trace-rows");document.querySelectorAll(".source-code-row").forEach(row=>{const line=Number(row.dataset.line),unit=unitForLine(line),inside=active&&line>=active.line&&line<=(active.lineEnd??active.line),traceRow=traceArea?.querySelector('.source-trace-row[data-line="'+line+'"]');applyRowState(row,"source-code-row",line,unit,inside,active);if(traceRow){applyRowState(traceRow,"source-trace-row",line,unit,inside,active);loopRows.render(traceRow.querySelector(".trace-note"),line)}})};
    const syncVertical=(from,to)=>{if(to.scrollTop!==from.scrollTop)to.scrollTop=from.scrollTop};
    const renderSource=()=>{const area=document.getElementById("source-lines"),traceArea=document.getElementById("trace-panel");area.replaceChildren();traceArea.replaceChildren();const lines=sourceLines();if(!lines.length){area.append(el("div","empty","表示できるコードがありません。"));return}const codePane=el("div","source-pane source-code-pane"),tracePane=el("div","source-pane source-trace-pane"),codeRows=el("div","source-pane-rows"),traceRows=el("div","source-pane-rows");codePane.tabIndex=tracePane.tabIndex=0;codePane.setAttribute("aria-label","コード");tracePane.setAttribute("aria-label","実行トレース");codeRows.id="source-code-rows";traceRows.id="source-trace-rows";lines.forEach(entry=>{const codeRow=el("div","source-row source-code-row"),traceRow=el("div","source-row source-trace-row");codeRow.dataset.line=traceRow.dataset.line=entry.line;codeRow.append(el("span","line-no",entry.line));const cell=el("span","code-cell");cell.append(codeWithSymbols(entry.text,entry.line));codeRow.append(cell);traceRow.append(el("span","trace-note"));codeRows.append(codeRow);traceRows.append(traceRow)});codePane.append(codeRows);tracePane.append(traceRows);codePane.addEventListener("scroll",()=>syncVertical(codePane,tracePane),{passive:true});tracePane.addEventListener("scroll",()=>syncVertical(tracePane,codePane),{passive:true});area.append(codePane);traceArea.append(tracePane);applySource()};
    const focusItem=item=>{selectedId=item.id;document.querySelectorAll(".card,.group-title").forEach(node=>node.classList.toggle("active",node.dataset.id===selectedId));applySource();document.querySelector('.source-row[data-line="'+item.line+'"]')?.scrollIntoView({block:"center",behavior:"smooth"})};
    const expansionBody=item=>{if(!item.expansion||item.expanded===false)return null;const box=el("div","expansion");box.style.setProperty("--accent",itemColor(item));const overview=item.expansion.overview;if(overview){const rows=item.kind==="class"?[["役割",overview.purpose],["状態",overview.state],["主な機能",overview.behavior]]:[["目的",overview.purpose],["入力",overview.input],["出力",overview.output]];if(overview.note)rows.push(["補足",overview.note]);rows.filter(([,value])=>value).forEach(([key,value])=>{const row=el("div","expansion-row");row.append(el("div","expansion-key",key),el("div","",value));box.append(row)})}(item.expansion.blocks||[]).forEach(block=>{const node=el("div","block");node.append(el("span","block-lines","L"+block.lineStart+"–"+block.lineEnd),el("strong","",block.label),el("div","",block.description));node.onclick=()=>{selectedId=item.id;applySource();document.querySelector('.source-row[data-line="'+block.lineStart+'"]')?.scrollIntoView({block:"center"})};box.append(node)});return box};
    const expand=async(button,item)=>{button.disabled=true;setStatus(item.label+" を分解しています…");try{const response=await fetch("/view/"+viewId+"/expand",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({line:item.line})});if(!response.ok)throw new Error(await response.text());standard=(await response.json()).standard;selectedId=item.id;renderCards();applySource();setStatus(item.label+" の説明を展開しました。")}catch(error){setStatus(error?.message||"分解できませんでした。",true)}finally{button.disabled=false}};
    const renderCards=()=>{const area=document.getElementById("cards");area.replaceChildren();const items=[...(standard.items||[])].sort((a,b)=>a.line-b.line);if(!items.length){area.append(el("div","empty","標準ビューはありません。"));return}items.forEach(item=>{const cardNode=el("div","card"+(item.parent?" child":""));cardNode.dataset.id=item.id;cardNode.style.setProperty("--accent",itemColor(item));cardNode.append(el("span","kind",kindLabel(item)),el("span","label",String(item.label).replace(/^class\\s+/,"").split("(")[0]));if(item.kind!=="constant"){const button=el("button","expand-button",item.expansion&&item.expanded!==false?"▼":"▶");button.title=item.expansion&&item.expanded!==false?"詳細を閉じる":"内部を分解";button.onclick=event=>{event.stopPropagation();if(item.expansion){item.expanded=item.expanded===false;renderCards();return}expand(button,item)};cardNode.append(button)}cardNode.onclick=()=>focusItem(item);area.append(cardNode);const body=expansionBody(item);if(body)area.append(body)});const active=itemById(selectedId);if(active){document.querySelectorAll(".card,.group-title").forEach(node=>node.classList.toggle("active",node.dataset.id===selectedId));applySource()}};
    const setTab=name=>{activeTab=name;document.querySelectorAll(".tab").forEach(tab=>tab.classList.toggle("active",tab.dataset.tab===name));document.querySelectorAll(".panel").forEach(panel=>panel.classList.remove("active"));document.getElementById(name+"-panel")?.classList.add("active")};const tabs=document.getElementById("tabs");const addTab=(name,label)=>{if(tabs.querySelector('[data-tab="'+name+'"]'))return;const tab=el("button","tab",label);tab.dataset.tab=name;tab.onclick=()=>setTab(name);tabs.append(tab)};if(data.trace)addTab("trace","実行トレース");if(data.standard)addTab("standard","標準ビュー");if(data.diagram)addTab("diagram","コード図");
    const workspace=document.getElementById("workspace"),header=document.getElementById("header"),toggle=document.getElementById("toggle-sidebar");const hasSidebar=Boolean(data.trace||data.standard||data.diagram);const setSidebarHidden=hidden=>{workspace.classList.toggle("sidebar-hidden",hidden);header.classList.toggle("sidebar-hidden",hidden);toggle.textContent=hidden?"サイドバーを開く":"サイドバーをしまう";toggle.setAttribute("aria-pressed",String(hidden));try{sessionStorage.setItem("ai-code-guide:combined-sidebar-hidden",String(hidden))}catch{}};toggle.onclick=()=>setSidebarHidden(!workspace.classList.contains("sidebar-hidden"));if(!hasSidebar){toggle.hidden=true;setSidebarHidden(true)}else{try{setSidebarHidden(sessionStorage.getItem("ai-code-guide:combined-sidebar-hidden")==="true")}catch{setSidebarHidden(false)}};
    document.getElementById("title").textContent=data.file||standard.title||"Pythonコード";document.getElementById("title").title=data.file||standard.title||"Pythonコード";if(data.diagram)document.getElementById("diagram-summary").textContent=data.diagram.summary||"";renderSource();if(data.standard)renderCards();if(hasSidebar)setTab(activeTab);
    {document.getElementById("diagram-panel").addEventListener("click",event=>{const shape=event.target.closest(".pd-flow-shape");if(shape){event.preventDefault();selectProjectDiagramShape(shape)}const jump=event.target.closest(".pd-detail-jump,.pd-node-jump");if(!jump)return;const node=jump.closest(".pd-node[data-line]")||document.querySelector('.pd-flow-shape[data-node-id="'+jump.dataset.nodeId+'"]');const line=Number(node?.dataset.line);if(Number.isSafeInteger(line)){document.querySelector('.source-row[data-line="'+line+'"]')?.scrollIntoView({block:"center"});document.querySelectorAll(".source-row").forEach(row=>row.classList.toggle("diagram-target",Number(row.dataset.line)===line))}})};
    // AI_NOTE: 名称のダブルクリックは文字選択。先行するclick/focusで開いたカードを残して読書を遮らない。
    document.addEventListener("selectionchange",()=>{const selection=getSelection();if(selection?.toString()&&document.getElementById("source").contains(selection.anchorNode)){pinnedKey=null;hideCard()}});
    card.onmouseenter=cancelHide;card.onmouseleave=scheduleHide;document.addEventListener("click",event=>{if(!pinnedKey)return;if(event.target.closest?.(".symbol-card,.symbol-anchor"))return;pinnedKey=null;card.hidden=true});document.addEventListener("keydown",event=>{if(event.key==="Escape"){pinnedKey=null;card.hidden=true}});window.addEventListener("resize",()=>{if(activeAnchor&&!card.hidden)positionCard(activeAnchor)});
    // AI_NOTE: 後着更新はコードDOMを保持し、名称・背景・実行値・図を独立に差し込む。
    let inlineFingerprint=JSON.stringify(annotations),traceFingerprint=JSON.stringify(data.trace),diagramFingerprint=JSON.stringify(data.diagram);
    const decorateNames=()=>decorateInlineNames(annotations,(anchor,item,pinned)=>{if(pinned)pinnedKey=item.symbolKey;if(!pinnedKey||pinned)showSymbol(anchor,item,pinned,(conversations[item.symbolKey]||[]).length>0);anchor.onmouseleave=scheduleHide;anchor.onblur=scheduleHide});
    decorateNames();
    installGenerationNotice({initial:data,onState:next=>{if(next.standard){const oldDetails=JSON.stringify(standard.items.map(item=>item.expansion));const previous=new Map(standard.items.map(item=>[item.id,item]));standard={...next.standard,items:next.standard.items.map(item=>{const prior=previous.get(item.id);return prior?.expansion&&JSON.stringify(prior.meaningRanges??standard.backgroundRanges)===JSON.stringify(item.meaningRanges??next.standard.backgroundRanges)?{...item,expansion:prior.expansion,expanded:prior.expanded}:{...item,expanded:false,expansion:undefined}})};if(oldDetails!==JSON.stringify(standard.items.map(item=>item.expansion)))renderCards();applySource()}if(next.annotations){const fingerprint=JSON.stringify(next.annotations.items);if(fingerprint!==inlineFingerprint){inlineFingerprint=fingerprint;annotations=next.annotations.items.filter(item=>item.kind==="symbol"&&item.symbolKey);Object.assign(conversations,next.annotations.conversations||{});decorateNames()}}if(next.trace){const fingerprint=JSON.stringify(next.trace);if(fingerprint!==traceFingerprint){traceFingerprint=fingerprint;traceFunctions=next.trace.functions||[];addTab("trace","実行トレース");applySource()}}if(next.diagram&&next.diagramHtml){const fingerprint=JSON.stringify(next.diagram);if(fingerprint!==diagramFingerprint){diagramFingerprint=fingerprint;const panel=document.getElementById("diagram-panel");panel.innerHTML=next.diagramHtml;const summary=el("p","diagram-summary",next.diagram.summary||"");panel.prepend(summary);addTab("diagram","コード図")}}}});
  </script>
</body>
</html>`;
}
