import type { AgentShowResult } from "./projectDiagramBridge";
import { sharedCodeSurfaceCss, sharedCodeSurfaceRuntime } from "./sharedCodeSurface";

export type StandardWebViewData = Pick<AgentShowResult, "file" | "line" | "standard">;

const safeJson = (value: unknown): string => JSON.stringify(value).replace(/</g, "\\u003c");

// AI_NOTE: CodexでもVS Code標準タブの読み方を変えない。左のコードと、右の定義順カード一覧を
// 常に同時表示し、クラス配下・カード内展開・概要ラベルの構造と色を揃える。
export function buildStandardWebView(data: StandardWebViewData, viewId: string): string {
    const initial = safeJson(data);
    const encodedViewId = safeJson(viewId);
    return `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>AI Code Guide · 標準</title>
  <style>
    :root{color-scheme:dark;--page:#181818;--side:#1e1e1e;--code:#161616;--text:#d4d4d4;--muted:#969696;--border:#3a3a3a;--focus:#4fc1ff;--keyword:#c586c0;--function:#dcdcaa;--string:#ce9178;--number:#b5cea8;--comment:#6a9955;--name:#9cdcfe;--type:#4ec9b0;--decorator:#dcdcaa;--line-height:21px}
    *{box-sizing:border-box}body{margin:0;background:var(--page);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button{font:inherit}.page{min-height:100vh}
    .header{display:flex;align-items:center;justify-content:space-between;gap:14px;height:64px;padding:11px 16px;border-bottom:1px solid var(--border);background:var(--side)}.eyebrow{margin:0 0 2px;color:#75a7ff;font-size:10px;font-weight:800;letter-spacing:.12em}.title{margin:0;font-size:16px;line-height:1.3}.summary{margin:2px 0 0;color:var(--muted);font-size:10px}.workspace{display:grid;grid-template-columns:minmax(430px,1.35fr) minmax(330px,.65fr);height:calc(100vh - 64px);min-height:460px}
    .source{min-width:0;overflow:auto;border-right:1px solid var(--border);background:var(--code);font:13px/var(--line-height) ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;scrollbar-gutter:stable}.source-row{display:grid;grid-template-columns:52px minmax(max-content,1fr);width:max-content;min-width:100%;border-left:3px solid transparent}.source-row.in-unit{border-left-color:var(--unit-color);background:color-mix(in srgb,var(--unit-color) 12%,transparent)}.source-row.selected{background:color-mix(in srgb,var(--unit-color) 20%,transparent)}.source-row.sub-block{background:color-mix(in srgb,var(--block-color) 18%,transparent)}.line-no{padding-right:11px;color:#707070;text-align:right;user-select:none}.code{min-width:max-content;padding-right:18px}.token-keyword{font-weight:650}
    ${sharedCodeSurfaceCss}
    .standard{min-width:0;overflow:auto;padding:0 10px 24px;background:var(--side);scrollbar-gutter:stable}.standard-head{position:sticky;top:0;z-index:5;margin:0 -10px 8px;padding:7px 10px;border-bottom:1px solid var(--border);background:var(--side)}.toolbar{display:flex;gap:4px;overflow-x:auto}.tbtn{flex:0 0 auto;padding:3px 8px;border:1px solid #555;border-radius:3px;color:var(--text);background:#303030;cursor:pointer;font-size:10px;white-space:nowrap}.tbtn:hover,.tbtn:focus-visible{border-color:var(--focus);outline:none}
    /* VS Code標準タブと同じ配色契約: 通常15%・muted 6%。子カードは8%のgroup-body上へ15%を重ねる。 */
    .cards{position:relative}.card{display:flex;align-items:center;gap:5px;min-height:34px;margin-bottom:4px;padding:6px 7px;border:0;border-left:3px solid var(--accent,#9d9d9d);border-radius:4px;background:color-mix(in srgb,var(--accent,#9d9d9d) 15%,transparent);cursor:pointer}.card:hover{filter:brightness(1.09)}.card.active,.group-block.active>.group-title{outline:2px solid var(--focus);outline-offset:-2px}.card.muted{border-left-width:2px;background:color-mix(in srgb,var(--accent,#9d9d9d) 6%,transparent);opacity:.82}.kind{flex:0 0 34px;color:var(--kind-color,var(--muted));font-size:10px}.label{min-width:0;flex:1;overflow-wrap:anywhere;white-space:normal;font:600 11px/1.35 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;user-select:text;cursor:text}.desc{flex-basis:100%;margin:2px 0 0 34px;color:var(--muted);font-size:11px;line-height:1.4}.card.has-desc{flex-wrap:wrap}.exp-btn,.class-overview{flex:0 0 auto;padding:5px 6px;margin:-5px -3px;border:0;color:var(--text);background:transparent;cursor:pointer;font-size:10px;opacity:.7}.exp-btn:hover,.class-overview:hover,.exp-btn.on,.class-overview.on{color:var(--focus);opacity:1}
    .group-block{margin-bottom:6px;border-radius:5px;overflow:hidden}.group-title{display:flex;align-items:center;gap:5px;padding:6px 8px;background:color-mix(in srgb,var(--accent,#4fc1ff) 22%,transparent);cursor:pointer;font-size:11px;font-weight:650}.group-title:hover{filter:brightness(1.08)}.group-toggle{flex:0 0 auto;font-size:10px;opacity:.7}.group-label{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;user-select:text;cursor:text}.group-count{color:var(--muted);font-size:9px}.group-desc{padding:0 8px 7px;background:color-mix(in srgb,var(--accent,#4fc1ff) 22%,transparent);color:#c7c7c7;font-size:11px;line-height:1.4}.group-body{display:flex;flex-direction:column;gap:0;background:color-mix(in srgb,var(--accent,#4fc1ff) 8%,transparent)}.group-body.collapsed{display:none}.group-body>.card,.group-body>.card-block,.group-body>.group-block{margin:0;border-radius:0}.group-body>.card:not(:last-child){border-bottom:1px solid color-mix(in srgb,var(--accent,#4fc1ff) 45%,transparent)}
    /* 展開部もVS Codeと同じ32%の継ぎ目＋12%の不透明カードにする。 */
    .card-block{margin-bottom:4px;border-radius:4px;overflow:hidden;background:color-mix(in srgb,var(--accent,#4fc1ff) 32%,var(--side))}.card-block>.card{margin:0 0 1px;border-radius:0;background:color-mix(in srgb,var(--accent,#4fc1ff) 12%,var(--side))}.subwrap{display:flex;flex-direction:column;gap:1px;padding-bottom:3px}.subover{padding:8px;border:1px solid color-mix(in srgb,var(--accent,#4fc1ff) 40%,var(--side));border-left:2px solid color-mix(in srgb,var(--accent,#4fc1ff) 55%,transparent);background:color-mix(in srgb,var(--accent,#4fc1ff) 12%,var(--side))}.so-row{font-size:11px;line-height:1.5}.so-row+.so-row{margin-top:6px}.so-key{display:inline-block;padding:0 7px;border:1px solid color-mix(in srgb,var(--row-color) 35%,transparent);border-radius:8px;color:var(--row-color);background:color-mix(in srgb,var(--row-color) 16%,transparent);font-size:9px;font-weight:650}.so-value{margin-top:2px}.subcard{padding:7px 9px;border:1px solid color-mix(in srgb,var(--accent,#4fc1ff) 40%,var(--side));border-left:3px solid var(--sub-color);background:color-mix(in srgb,var(--accent,#4fc1ff) 12%,var(--side));cursor:pointer}.subcard:hover{filter:brightness(1.1)}.sub-label{font-size:11px;font-weight:650}.sub-desc{margin-top:2px;color:#bdbdbd;font-size:11px;line-height:1.42}.sub-lines{float:right;margin-left:6px;color:var(--muted);font:9px/1.4 ui-monospace,monospace}.empty{padding:20px 10px;border:1px dashed var(--border);border-radius:6px;color:var(--muted);text-align:center;font-size:11px}.status{position:fixed;right:12px;bottom:10px;z-index:8;pointer-events:none;max-width:min(520px,calc(100vw - 24px));margin:0;padding:7px 10px;border:1px solid var(--border);border-radius:6px;color:#75a7ff;background:#292929;font-size:10px;box-shadow:0 4px 18px #0008}.status:empty{display:none}.status.error{color:#f48771}
    @media(max-width:760px){.workspace{display:block;height:auto}.source{height:46vh;border-right:0;border-bottom:1px solid var(--border)}.standard{height:48vh}.header{height:auto}.standard-head{top:0}}
  </style>
</head>
<body>
  <main class="page"><header class="header"><div><p class="eyebrow">AI CODE GUIDE · 標準</p><h1 class="title" id="title"></h1><p class="summary" id="summary"></p></div></header><section class="workspace"><section class="source" id="source" tabindex="0" aria-label="意味単位で色分けしたPythonコード全文"></section><aside class="standard" aria-label="VS Code標準タブと同じカード一覧"><header class="standard-head"><div class="toolbar"><button class="tbtn" id="open-groups">▼ クラスを開く</button><button class="tbtn" id="close-groups">▶ クラスを閉じる</button></div></header><div class="cards" id="cards"></div></aside></section><p class="status" id="status" role="status"></p></main>
  <script>
    const data=${initial};const viewId=${encodedViewId};let standard=data.standard||{source:[],items:[]};let selectedId="";let statusTimer=0;const blockPalette=["#4fc1ff","#f48771","#4ec9b0","#dcdcaa","#c586c0","#9cdcfe"];
    const el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=String(text);return node};const itemById=id=>(standard.items||[]).find(item=>item.id===id)||null;const children=id=>(standard.items||[]).filter(item=>item.parent===id).sort((a,b)=>a.line-b.line);const roots=()=>(standard.items||[]).filter(item=>!item.parent).sort((a,b)=>a.line-b.line);
    const itemColor=item=>item?.color||({class:"#c586c0",constant:"#dcdcaa",function:"#4ec9b0"}[item?.kind]||"#9d9d9d");const kindLabel=item=>item.kind==="class"?"クラス":item.kind==="constant"?"定数":"関数";const kindColor=item=>item.kind==="class"?"#c586c0":item.kind==="constant"?"#dcdcaa":"#4ec9b0";
    const setStatus=(text,error=false,hideAfter=0)=>{if(statusTimer){clearTimeout(statusTimer);statusTimer=0}const node=document.getElementById("status");node.textContent=text;node.classList.toggle("error",error);if(text&&hideAfter>0)statusTimer=setTimeout(()=>{node.textContent="";node.classList.remove("error");statusTimer=0},hideAfter)};
    ${sharedCodeSurfaceRuntime}
    const unitForLine=line=>(standard.items||[]).filter(item=>line>=item.line&&line<=(item.lineEnd??item.line)).sort((a,b)=>((a.lineEnd??a.line)-a.line)-((b.lineEnd??b.line)-b.line))[0]||null;const selected=()=>itemById(selectedId);const blockIndex=(line,item)=>item?.expansion?.blocks?.findIndex(block=>line>=block.lineStart&&line<=block.lineEnd)??-1;
    const applySource=()=>{const active=selected();document.querySelectorAll(".source-row").forEach(row=>{const line=Number(row.dataset.line),unit=unitForLine(line),index=blockIndex(line,active),inside=active&&line>=active.line&&line<=(active.lineEnd??active.line),showRangeFill=inside&&active?.kind!=="class";const color=index>=0?blockPalette[index%blockPalette.length]:itemColor(unit);row.className="source-row"+(unit?" in-unit":"")+(showRangeFill?" selected":"")+(index>=0?" sub-block":"");row.style.setProperty("--unit-color",color);row.style.setProperty("--block-color",color)})};
    const applyCardSelection=()=>{document.querySelectorAll(".card").forEach(card=>card.classList.toggle("active",card.dataset.id===selectedId));document.querySelectorAll(".group-block").forEach(group=>group.classList.toggle("active",group.dataset.id===selectedId))};
    // Keep the clicked card DOM alive. Replacing it here destroys a human double-click selection
    // when the second click arrives after the former short single-click delay.
    const focusItem=(item,line=item.line)=>{selectedId=item.id;applyCardSelection();applySource();const row=document.querySelector('.source-row[data-line="'+line+'"]');row?.scrollIntoView({block:"center",behavior:"smooth"})};
    const nameTarget=(event,container)=>{const target=event.target instanceof Element?event.target.closest(".label,.group-label"):null;return target&&container.contains(target)?target:null};
    const selectableDoubleClick=(event,container)=>{const target=nameTarget(event,container);if(!target)return;event.preventDefault();event.stopPropagation();const range=document.createRange();range.selectNodeContents(target);const selection=window.getSelection();selection?.removeAllRanges();selection?.addRange(range)};
    // The source pane behaves like a normal editor: clicking or double-clicking code only moves
    // the caret/selection. Navigation and centering belong exclusively to the guide cards.
    const renderSource=()=>{const pane=document.getElementById("source");pane.replaceChildren();(standard.source||[]).forEach(entry=>{const row=el("div","source-row"),number=el("span","line-no",entry.line),code=el("code","code");row.dataset.line=String(entry.line);codeSurface.appendPython(code,entry.text);row.append(number,code);pane.append(row)});applySource()};
    const expand=async(button,item)=>{button.disabled=true;setStatus(item.label+" を分解しています…");try{const response=await fetch("/view/"+viewId+"/expand",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({line:item.line})});if(!response.ok)throw new Error(await response.text()||"分解できませんでした。");standard=(await response.json()).standard;selectedId=item.id;renderSource();renderCards();setStatus(item.label+" の説明を展開しました。",false,2400)}catch(error){setStatus(error?.message||"分解できませんでした。",true,6000);button.disabled=false}};
    const overviewBox=(overview,item)=>{if(!overview)return null;const box=el("div","subover"),rows=item.kind==="class"?[["役割",overview.purpose,"#4fc1ff"],["状態",overview.state,"#73c991"],["主な機能",overview.behavior,"#e2b93d"]]:[["目的",overview.purpose,"#4fc1ff"],["入力",overview.input,"#73c991"],["出力",overview.output,"#e2b93d"]];if(overview.note)rows.push(["補足",overview.note,"#f0a500"]);rows.filter(([,value])=>value).forEach(([label,value,color])=>{const row=el("div","so-row"),key=el("span","so-key",label);key.style.setProperty("--row-color",color);row.append(key,el("div","so-value",value));box.append(row)});return box};
    const expansionBody=item=>{const wrap=el("div","subwrap");const expansion=item.expansion;if(!expansion)return wrap;const overview=overviewBox(expansion.overview,item);if(overview)wrap.append(overview);(expansion.blocks||[]).forEach((block,index)=>{const card=el("div","subcard"),lines=el("span","sub-lines","L"+block.lineStart+"–"+block.lineEnd);card.style.setProperty("--sub-color",blockPalette[index%blockPalette.length]);card.append(lines,el("div","sub-label",block.label),el("div","sub-desc",block.description));card.onclick=event=>{event.stopPropagation();focusItem(item,block.lineStart)};wrap.append(card)});return wrap};
    const plainCard=item=>{const card=el("div","card"+(item.description?" has-desc":"")+(item.kind==="constant"?" muted":""));card.dataset.id=item.id;card.style.setProperty("--accent",itemColor(item));card.style.setProperty("--kind-color",kindColor(item));card.classList.toggle("active",selectedId===item.id);card.append(el("span","kind",kindLabel(item)),el("span","label",String(item.label).split("(")[0]));if(item.kind!=="constant"){const expandButton=el("button","exp-btn"+(item.expansion?" on":""),item.expansion?"▼":"▶");expandButton.type="button";expandButton.title="内部を分解";expandButton.onclick=event=>{event.stopPropagation();expand(expandButton,item)};card.append(expandButton)}if(item.description)card.append(el("div","desc",item.description));card.onclick=()=>focusItem(item);card.ondblclick=event=>selectableDoubleClick(event,card);if(!item.expansion)return card;const block=el("div","card-block");block.style.setProperty("--accent",itemColor(item));block.append(card,expansionBody(item));return block};
    const classGroup=item=>{const kids=children(item.id);if(kids.length===0)return plainCard(item);const group=el("section","group-block"+(selectedId===item.id?" active":""));group.dataset.id=item.id;group.style.setProperty("--accent",itemColor(item));const title=el("header","group-title"),toggle=el("span","group-toggle","▼"),label=el("span","group-label",String(item.label).replace(/^class\\s+/,"").split("(")[0]),count=el("span","group-count",kids.length),overview=el("button","class-overview"+(item.expansion?" on":""),"概要 "+(item.expansion?"▼":"▶"));overview.type="button";overview.onclick=event=>{event.stopPropagation();expand(overview,item)};title.append(toggle,label,count,overview);const body=el("div","group-body");kids.forEach(child=>body.append(renderItem(child)));const selectGroup=()=>{focusItem(item);const closed=body.classList.toggle("collapsed");toggle.textContent=closed?"▶":"▼"};title.onclick=selectGroup;title.ondblclick=event=>selectableDoubleClick(event,title);group.append(title);if(item.description)group.append(el("div","group-desc",item.description));if(item.expansion)group.append(expansionBody(item));group.append(body);return group};
    const renderItem=item=>item.kind==="class"?classGroup(item):plainCard(item);const renderCards=()=>{const area=document.getElementById("cards");area.replaceChildren();const list=roots();if(!list.length)area.append(el("div","empty","表示できる構造がありません"));else list.forEach(item=>area.append(renderItem(item)))};
    const setGroups=closed=>{document.querySelectorAll(".group-body").forEach(body=>{body.classList.toggle("collapsed",closed);const toggle=body.closest(".group-block")?.querySelector(".group-toggle");if(toggle)toggle.textContent=closed?"▶":"▼"})};document.getElementById("open-groups").onclick=()=>setGroups(false);document.getElementById("close-groups").onclick=()=>setGroups(true);
    document.getElementById("title").textContent=standard.title||data.file||"Pythonコード";document.getElementById("summary").textContent=data.file||"";const focusLine=Number(data.line);if(Number.isSafeInteger(focusLine)){const focus=(standard.items||[]).filter(item=>focusLine>=item.line&&focusLine<=(item.lineEnd??item.line)).sort((a,b)=>(a.lineEnd-a.line)-(b.lineEnd-b.line))[0];if(focus)selectedId=focus.id}renderSource();renderCards();if(Number.isSafeInteger(focusLine)){document.querySelector('.source-row[data-line="'+focusLine+'"]')?.scrollIntoView({block:"center",inline:"nearest"})}
  </script>
</body>
</html>`;
}
