// AI_NOTE: 会話内ではファイル全体を再現せず、解説・実行値に関係する数行だけを構文色付きで見せる。
// トレースはコード欄と実行値欄を独立した横スクロール面にし、固定高の行どうしを対応させる。
export function buildCodeEvidenceAppShell(): string {
  return `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root { color-scheme:light dark; --surface:Canvas; --text:CanvasText; --muted:color-mix(in srgb,CanvasText 64%,transparent); --border:color-mix(in srgb,CanvasText 18%,transparent); --code:#1f1f1f; --editor-text:#d4d4d4; --editor-muted:#858585; --keyword:#c586c0; --function:#dcdcaa; --string:#ce9178; --number:#b5cea8; --comment:#6a9955; --name:#9cdcfe; --type:#4ec9b0; --decorator:#dcdcaa; --info:#e2b93d; --warning:#f48771; --trace:#9cdcfe; --editor-font:Consolas,"Courier New",monospace; --editor-font-size:14px; --editor-line-height:20px; }
  * { box-sizing:border-box; } body { margin:0; min-height:150px; color:var(--text); background:var(--surface); font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; } #status { margin:0; padding:22px 16px; text-align:center; opacity:.7; } #app { display:none; padding:16px; } body.ready #status { display:none; } body.ready #app { display:block; } body.error #status { color:var(--warning); opacity:1; }
  .header { display:flex; justify-content:space-between; gap:12px; align-items:center; margin-bottom:12px; } .title { margin:0; font-size:18px; line-height:1.35; overflow-wrap:anywhere; } .header-actions { display:flex; align-items:center; gap:8px; } .kind { color:var(--muted); font-size:11px; white-space:nowrap; } .fullscreen { flex:0 0 auto; padding:5px 8px; border:1px solid var(--border); border-radius:7px; color:var(--text); background:var(--surface); font:inherit; font-size:11px; cursor:pointer; white-space:nowrap; } .fullscreen:disabled { opacity:.65; cursor:wait; } .list { display:flex; flex-direction:column; gap:12px; }
  .evidence { overflow:hidden; border:1px solid var(--border); border-radius:10px; } .evidence-head { display:flex; justify-content:space-between; gap:10px; align-items:flex-start; padding:9px 10px; border-bottom:1px solid var(--border); } .label { font:650 13px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace; overflow-wrap:anywhere; } .meta { margin-top:3px; color:var(--muted); font-size:10px; } .open { flex:0 0 auto; min-width:88px; min-height:36px; padding:7px 12px; border:1px solid var(--border); border-radius:7px; color:var(--text); background:var(--surface); font:inherit; font-size:11px; font-weight:650; cursor:pointer; } .open:hover, .open:focus-visible { border-color:var(--trace); outline:2px solid color-mix(in srgb,var(--trace) 24%,transparent); outline-offset:2px; } .open:disabled { opacity:.65; cursor:wait; }
  .code-grid { width:100%; overflow-x:auto; overflow-y:hidden; background:var(--code); scrollbar-color:color-mix(in srgb,var(--editor-text) 42%,transparent) transparent; } .code-grid::-webkit-scrollbar { height:10px; } .code-grid::-webkit-scrollbar-track { background:color-mix(in srgb,var(--editor-text) 5%,transparent); } .code-grid::-webkit-scrollbar-thumb { border:2px solid transparent; border-radius:999px; background:color-mix(in srgb,var(--editor-text) 42%,transparent); background-clip:padding-box; } .code-row { display:grid; grid-template-columns:38px minmax(720px,1fr) minmax(240px,38%); width:max-content; min-width:100%; min-height:29px; } .code-row.target { box-shadow:inset 3px 0 var(--info); background:color-mix(in srgb,var(--info) 8%,var(--code)); } .code-row.target.warning { box-shadow:inset 3px 0 var(--warning); background:color-mix(in srgb,var(--warning) 7%,var(--code)); } .line { padding:6px 7px 6px 3px; color:var(--editor-muted); font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace; text-align:right; user-select:none; } .code { display:block; min-width:max-content; padding:6px 9px 6px 3px; color:var(--editor-text); background:transparent; font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace; white-space:pre; overflow:visible; } .note { min-width:0; padding:6px 8px; border-left:1px solid var(--border); color:var(--editor-muted); font-size:11px; line-height:1.45; overflow-wrap:anywhere; } .note strong { color:var(--editor-text); font-weight:650; } .value { color:var(--trace); font-family:ui-monospace,SFMono-Regular,Menlo,monospace; } .gap { grid-column:1/-1; padding:2px 12px; color:var(--editor-muted); font-size:10px; text-align:center; }
  .trace-grid { display:grid; grid-template-columns:minmax(0,62%) minmax(0,38%); background:var(--code); } .trace-pane { min-width:0; overflow-x:auto; overflow-y:hidden; scrollbar-width:thin; scrollbar-color:color-mix(in srgb,var(--editor-text) 32%,transparent) transparent; } .trace-pane::-webkit-scrollbar { height:8px; } .trace-pane::-webkit-scrollbar-track { background:transparent; } .trace-pane::-webkit-scrollbar-thumb { border-radius:999px; background:color-mix(in srgb,var(--editor-text) 32%,transparent); } .trace-note-pane { position:relative; z-index:1; border-left:2px solid #555; overflow-x:auto; background:var(--code); } .trace-lines { display:grid; width:max-content; min-width:100%; } .trace-row { display:flex; align-items:center; width:100%; height:var(--editor-line-height); min-height:var(--editor-line-height); white-space:nowrap; } .trace-code-row .code { min-width:max-content; padding:0 9px 0 0; overflow:visible; font:var(--editor-font-size)/var(--editor-line-height) var(--editor-font); } .trace-note-row { width:max-content; min-width:100%; min-height:var(--editor-line-height); padding:0 10px; color:var(--editor-muted); font:var(--editor-font-size)/var(--editor-line-height) var(--editor-font); white-space:nowrap; overflow:visible; } .trace-gap { min-height:var(--editor-line-height); justify-content:center; padding:0 12px; color:var(--editor-muted); font-size:10px; }
  .token-keyword { color:var(--keyword); } .token-function { color:var(--function); } .token-string { color:var(--string); } .token-number { color:var(--number); } .token-comment { color:var(--comment); } .token-type { color:var(--type); } .token-decorator { color:var(--decorator); } .token-name { color:var(--name); }
  .loop { display:inline-flex; flex:0 0 auto; align-items:center; gap:3px; height:var(--editor-line-height); margin-right:5px; color:var(--info); font:650 var(--editor-font-size)/var(--editor-line-height) var(--editor-font); white-space:nowrap; } .loop button { width:18px; height:18px; padding:0; border:1px solid var(--border); border-radius:4px; color:var(--text); background:var(--surface); font-size:9px; line-height:16px; cursor:pointer; } .loop button:disabled { opacity:.35; cursor:default; } .limit { padding:7px 9px; border-top:1px solid var(--border); color:var(--muted); font-size:10px; }
  .empty { padding:18px 12px; border:1px dashed var(--border); border-radius:9px; color:var(--muted); font-size:12px; text-align:center; } .jump-status { min-height:18px; margin:10px 2px 0; color:var(--trace); font-size:11px; } .jump-status.error { color:var(--warning); }
  @media (max-width:560px) { #app { padding:10px; } .header{align-items:flex-start}.header-actions{flex-direction:column-reverse;align-items:flex-end;gap:4px}.code-row{grid-template-columns:32px minmax(600px,1fr) minmax(220px,38%)}.trace-grid{grid-template-columns:minmax(0,58%) minmax(0,42%)}.evidence-head{align-items:center} }
</style></head><body><p id="status" role="status">コードを読み込んでいます…</p><main id="app" aria-live="polite"><header class="header"><h2 class="title" id="title"></h2><span class="header-actions"><span class="kind" id="kind"></span><button class="fullscreen" id="fullscreen" type="button">横に広げる</button></span></header><section class="list" id="content"></section><p class="jump-status" id="jump-status" role="status"></p></main>
<script>
  const pending=new Map();let nextId=1,workspaceRoot="",sourceFile="";
  const request=(method,params)=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});window.parent.postMessage({jsonrpc:"2.0",id,method,params},"*");});
  const notify=(method,params)=>window.parent.postMessage({jsonrpc:"2.0",method,params},"*");
  const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;};
  const absolute=(file)=>{const windows=file.length>2&&file[1]===":"&&(file[2]==="/"||file.charCodeAt(2)===92);return !workspaceRoot||file.startsWith("/")||windows?file:workspaceRoot.replace(/[\\/]$/,"")+"/"+file.replace(/^[\\/]/,"");};
  const setStatus=(text,error=false)=>{const node=document.getElementById("jump-status");node.textContent=text;node.classList.toggle("error",error);};
  const openFullscreen=(button)=>{const display=window.openai?.requestDisplayMode;if(typeof display!=="function"){setStatus("この環境では横幅の拡大を利用できません。",true);return;}button.disabled=true;Promise.resolve(display.call(window.openai,{mode:"fullscreen"})).catch((error)=>setStatus(error?.message||"表示を広げられませんでした。",true)).finally(()=>{button.disabled=false;});};
  const openCode=(line,button)=>{button.disabled=true;setStatus("VS Codeでコードを開いています…");request("tools/call",{name:"show_standard_view",arguments:{file:absolute(sourceFile),line,focusWindow:true}}).then((result)=>{if(result?.isError)throw new Error(result?.content?.[0]?.text||"コードを開けませんでした。");const receipt=result?.structuredContent?.jumpReceipt;if(!receipt||receipt.acknowledged!==true||receipt.line!==line||receipt.selectionEmpty!==true||typeof receipt.receiptId!=="string"||!receipt.receiptId)throw new Error("VS Codeの対象行への到達確認を受け取れませんでした。");setStatus("VS Codeで "+sourceFile+":"+line+" を開きました。確認: "+receipt.receiptId);}).catch((error)=>setStatus(error?.message||"コードを開けませんでした。",true)).finally(()=>{button.disabled=false;});};
  const keywords=new Set("False None True and as assert async await break class continue def del elif else except finally for from global if import in is lambda nonlocal not or pass raise return try while with yield".split(" "));
  const types=new Set("bool bytes dict float frozenset int list object set str tuple type".split(" "));
  const python=(text)=>{const root=el("span","code",undefined);const pattern=/(@[A-Za-z_]\\w*(?:\\.[A-Za-z_]\\w*)*|#[^\\n]*|"(?:\\\\.|[^"\\\\])*"|'(?:\\\\.|[^'\\\\])*'|\\b\\d+(?:\\.\\d+)?\\b|\\b[A-Za-z_]\\w*(?=\\s*\\()|\\b[A-Za-z_]\\w*\\b)/g;let last=0;for(const match of text.matchAll(pattern)){if(match.index>last)root.append(document.createTextNode(text.slice(last,match.index)));const token=match[0];const before=text.slice(0,match.index);let cls="";if(token.startsWith("@"))cls="token-decorator";else if(token.startsWith("#"))cls="token-comment";else if(token.startsWith('"')||token.startsWith("'"))cls="token-string";else if(/^\\d/.test(token))cls="token-number";else if(keywords.has(token))cls="token-keyword";else if(/\\bclass\\s*$/.test(before)||types.has(token)||/^[A-Z]\\w*$/.test(token))cls="token-type";else if(/\\bdef\\s*$/.test(before)||/^\\s*\\(/.test(text.slice(match.index+token.length)))cls="token-function";else if(token==="self"||token==="cls")cls="token-name";const span=el("span",cls,token);root.append(span);last=match.index+token.length;}if(last<text.length)root.append(document.createTextNode(text.slice(last)));return root;};
  const gap=()=>{const row=el("div","code-row",undefined);row.append(el("span","gap","… 省略 …"));return row;};
  const rows=(lines,noteFor)=>{const grid=el("div","code-grid",undefined);let previous=0;(lines||[]).forEach((line)=>{if(previous&&line.line>previous+1)grid.append(gap());const note=noteFor(line.line);const row=el("div","code-row"+(note.target?" target":"")+(note.warning?" warning":""),undefined);row.append(el("span","line",String(line.line)),python(line.text));const side=el("span","note",undefined);if(note.title)side.append(el("strong","",note.title));if(note.title&&note.text)side.append(document.createElement("br"));if(note.loop)side.append(note.loop);if(note.text)side.append(el("span",note.value?"value":"",note.text));row.append(side);grid.append(row);previous=line.line;});return grid;};
  const traceRows=(lines,noteFor)=>{const visible=lines||[];const indents=visible.filter((line)=>line.text.trim()).map((line)=>(line.text.match(/^[ \t]*/)||[""])[0].length);const baseIndent=indents.length?Math.min(...indents):0;const grid=el("div","trace-grid",undefined);const codePane=el("div","trace-pane trace-code-pane",undefined);const notePane=el("div","trace-pane trace-note-pane",undefined);const codeLines=el("div","trace-lines trace-code-lines",undefined);const noteLines=el("div","trace-lines trace-note-lines",undefined);let previous=0;visible.forEach((line)=>{if(previous&&line.line>previous+1){codeLines.append(el("div","trace-row trace-gap","… 省略 …"));noteLines.append(el("div","trace-row trace-gap","… 省略 …"));}const note=noteFor(line.line);const codeRow=el("div","trace-row trace-code-row",undefined);codeRow.append(python(line.text.slice(baseIndent)));const noteRow=el("div","trace-row trace-note-row",undefined);if(note.loop)noteRow.append(note.loop);if(note.text)noteRow.append(el("span",note.value?"value":"",note.text));codeLines.append(codeRow);noteLines.append(noteRow);previous=line.line;});codePane.append(codeLines);notePane.append(noteLines);grid.append(codePane,notePane);return grid;};
  const shell=(label,meta,line)=>{const article=el("article","evidence",undefined);const head=el("header","evidence-head",undefined);const text=el("div","",undefined);text.append(el("div","label",label),el("div","meta",meta));const button=el("button","open","コードへ");button.type="button";button.tabIndex=0;button.setAttribute("role","button");button.setAttribute("aria-label",label+" のコードへ移動");button.setAttribute("title","VS Codeで "+label+" のコードを開く");button.addEventListener("click",()=>openCode(line,button));head.append(text,button);article.append(head);return article;};
  const renderAnnotations=(data)=>{const list=document.getElementById("content");if(!data.items?.length){list.append(el("div","empty","保存済みの名称辞書はありません。"));return;}data.items.forEach((item)=>{const article=shell(item.label,"名称 · L"+item.startLine,item.startLine);article.append(rows(item.code,(line)=>({target:line===item.startLine,warning:false,title:line===item.startLine?item.label:"",text:line===item.startLine?item.explanation:""})));list.append(article);});};
  const renderTraceFunction=(fn)=>{const article=shell(fn.funcName+"()","実行トレース · L"+fn.startLine+"–"+fn.endLine,fn.startLine);article.classList.add("trace-evidence");let index=0;const draw=()=>{const existing=article.querySelector(".trace-grid");const iteration=fn.iterations[index]||{values:[]};const values=new Map(iteration.values.map((value)=>[value.line,value.text]));const paths=new Map((fn.pathEvents||[]).map((event)=>[event.line,event.outcome]));const grid=traceRows(fn.code,(line)=>{const value=values.get(line)||"";const path=paths.has(line)?"条件: "+(paths.get(line)?"true":"false"):"";const text=[path,value].filter(Boolean).join(" · ");if(!fn.loop||line!==fn.loop.headerLine)return{text,value:Boolean(value)};const control=el("span","loop",undefined);const previous=el("button","","◀");const label=el("span","",(index+1)+"周目 / 全"+fn.loop.actualTotal+"周");const next=el("button","","▶");previous.type=next.type="button";previous.disabled=index===0;next.disabled=index>=fn.iterations.length-1;previous.addEventListener("click",()=>{index--;draw();});next.addEventListener("click",()=>{index++;draw();});control.append(previous,label,next);return{loop:control,text,value:Boolean(value)};});if(existing)existing.replaceWith(grid);else article.append(grid);};draw();if(fn.loop&&fn.loop.actualTotal>fn.loop.total)article.append(el("div","limit","最初の"+fn.loop.total+"周を表示しています。残りはVS Codeで確認できます。"));return article;};
  const renderTrace=(data)=>{const list=document.getElementById("content");if(!data.functions?.length){list.append(el("div","empty","実行トレースはありません。"));return;}(data.functions||[]).forEach((fn)=>list.append(renderTraceFunction(fn)));};
  const render=(result)=>{try{const value=result?.result??result;if(value?.isError)throw new Error(value?.content?.find((item)=>item?.type==="text")?.text||"表示できませんでした。");const data=value?.structuredContent||{};const meta=value?._meta??value?.meta;workspaceRoot=typeof meta?.guideWorkspaceRoot==="string"?meta.guideWorkspaceRoot:"";sourceFile=typeof data.file==="string"?data.file:"";document.getElementById("title").textContent=sourceFile||"Pythonコード";if(data.annotations){document.getElementById("kind").textContent="インライン解説";renderAnnotations(data.annotations);}else if(data.trace){document.getElementById("kind").textContent="実行トレース";renderTrace(data.trace);}else throw new Error("コード表示データを受け取れませんでした。");document.body.classList.remove("error");document.body.classList.add("ready");}catch(error){document.getElementById("status").textContent=error?.message||"表示できませんでした。";document.body.classList.remove("ready");document.body.classList.add("error");}};
  window.addEventListener("message",(event)=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(message.id!==undefined&&pending.has(message.id)){const item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(message.error):item.resolve(message.result);return;}if(message.method==="ui/notifications/tool-result")render(message.params);},{passive:true});
  const fullscreen=document.getElementById("fullscreen");fullscreen.addEventListener("click",()=>openFullscreen(fullscreen));
  request("ui/initialize",{appInfo:{name:"ai-code-guide-evidence",version:"0.1.0"},appCapabilities:{},protocolVersion:"2026-01-26"}).then(()=>notify("ui/notifications/initialized",{})).catch(()=>{document.getElementById("status").textContent="表示を初期化できませんでした。";document.body.classList.add("error");});
</script></body></html>`;
}
