// AI_NOTE: 概要・構成・解説・トレースは同じMCP Appで描画する。データ取得を増やさず、
// VS Codeの各タブと同じ「見出し→色付きカード→コード地点へ移動」の読み方を会話内へ移す。
export function buildDetailAppShell(): string {
    return `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root { color-scheme:light dark; --accent:#4fc1ff; --function:#4ec9b0; --class:#c586c0; --warning:#e2b93d; --danger:#f14c4c; --line:color-mix(in srgb,CanvasText 18%,transparent); --soft:color-mix(in srgb,CanvasText 5%,Canvas); --muted:color-mix(in srgb,CanvasText 64%,transparent); }
  * { box-sizing:border-box; } body { margin:0; min-height:150px; color:CanvasText; background:Canvas; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; } #status { margin:0; padding:22px 16px; text-align:center; opacity:.7; } #app { display:none; padding:16px; } body.ready #status { display:none; } body.ready #app { display:block; } body.error #status { color:var(--danger); opacity:1; }
  .header { margin-bottom:13px; } .eyebrow { margin:0 0 3px; color:var(--muted); font-size:10px; font-weight:700; letter-spacing:.06em; } .title { margin:0; font-size:18px; line-height:1.35; overflow-wrap:anywhere; } .role { margin:6px 0 0; padding-left:9px; border-left:3px solid var(--accent); color:var(--muted); font-size:12px; line-height:1.55; }
  .list { display:flex; flex-direction:column; gap:8px; } .group { overflow:hidden; border:1px solid var(--line); border-radius:9px; background:var(--soft); } .group-title { margin:0; padding:8px 10px; border-bottom:1px solid var(--line); font-size:12px; font-weight:700; } .group-items { display:flex; flex-direction:column; gap:5px; padding:7px; }
  button { font:inherit; } .card { --kind:var(--function); width:100%; display:grid; grid-template-columns:minmax(0,1fr) auto; gap:10px; align-items:center; padding:9px 10px; border:1px solid var(--line); border-left:4px solid var(--kind); border-radius:8px; color:CanvasText; background:Canvas; text-align:left; cursor:pointer; } .card.class { --kind:var(--class); } .card.constant { --kind:var(--warning); } .card.warning { --kind:var(--warning); } .card.danger { --kind:var(--danger); } .card:hover,.card:focus-visible { outline:2px solid color-mix(in srgb,var(--kind) 42%,transparent); outline-offset:1px; background:color-mix(in srgb,var(--kind) 9%,Canvas); } .card:disabled { opacity:.7; cursor:wait; }
  .name { font:650 13px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace; overflow-wrap:anywhere; } .meta { margin-top:3px; color:var(--muted); font-size:10px; line-height:1.35; } .description { margin-top:5px; color:color-mix(in srgb,CanvasText 80%,transparent); font-size:12px; line-height:1.5; } .action { color:var(--muted); font-size:10px; white-space:nowrap; } .annotation-range { min-width:44px; color:var(--muted); font:11px/1.3 ui-monospace,SFMono-Regular,Menlo,monospace; text-align:right; }
  .directory { margin:0 0 7px; color:var(--class); font-size:11px; font-weight:700; } .import,.relation,.order-item { margin:0; padding:7px 9px; border-left:2px solid var(--accent); color:var(--muted); font:11px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace; overflow-wrap:anywhere; } .relations,.reading-order,.imports { margin-top:12px; padding:10px; border:1px solid var(--line); border-radius:9px; } .relations h3,.reading-order h3,.imports h3 { margin:0 0 7px; font-size:12px; } .empty { padding:18px 12px; border:1px dashed var(--line); border-radius:9px; color:var(--muted); font-size:12px; text-align:center; } .jump-status { min-height:18px; margin:10px 2px 0; color:var(--accent); font-size:11px; } .jump-status.error { color:var(--danger); }
  .view-state { margin:0 0 7px; color:var(--muted); font:10px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace; }
  @media (max-width:520px) { #app { padding:10px; } .card { grid-template-columns:minmax(0,1fr); gap:4px; } .action,.annotation-range { text-align:left; } }
</style></head><body><p id="status" role="status">コード情報を表示しています…</p><main id="app" aria-live="polite"><p class="view-state" id="view-state" role="status"></p><header class="header"><p class="eyebrow" id="eyebrow"></p><h2 class="title" id="title"></h2><p class="role" id="role"></p></header><section id="content"></section><p class="jump-status" id="jump-status" role="status"></p></main>
<script>
  const pending=new Map(); let nextId=1, workspaceRoot="", sourceFile="";
  const request=(method,params)=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});window.parent.postMessage({jsonrpc:"2.0",id,method,params},"*");});
  const notify=(method,params)=>window.parent.postMessage({jsonrpc:"2.0",method,params},"*");
  const absolute=(file)=>{const windows=file.length>2&&file[1]===":"&&(file[2]==="/"||file.charCodeAt(2)===92);return !workspaceRoot||file.startsWith("/")||windows?file:workspaceRoot.replace(/[\\/]$/,"")+"/"+file.replace(/^[\\/]/,"");};
  const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text)node.textContent=text;return node;};
  const status=(text,error)=>{const node=document.getElementById("jump-status");node.textContent=text;node.classList.toggle("error",Boolean(error));};
  const open=(file,line,button)=>{if(!file){status("この項目には移動先がありません。",true);return;}button.disabled=true;status("VS Codeでコードを開いています…");request("tools/call",{name:"show_standard_view",arguments:{file:absolute(file),line:Math.max(1,Number(line)||1),focusWindow:true}}).then((result)=>{if(result?.isError)throw new Error(result?.content?.[0]?.text||"コードを開けませんでした。");status("VS Codeで "+file+":"+Math.max(1,Number(line)||1)+" を開きました。");}).catch((error)=>status(error?.message||"コードを開けませんでした。",true)).finally(()=>{button.disabled=false;});};
  const codeCard=(item,file,extra="")=>{const button=el("button","card "+(item.kind==="class"?"class":item.kind==="constant"?"constant":"")+(item.severity==="warning"?" danger":""),"");button.type="button";const text=el("div","","");text.append(el("div","name",item.label||item.path||"コード地点"));const meta=[extra,item.description].filter(Boolean);if(meta.length)text.append(el("div","meta",meta[0]));if(meta[1])text.append(el("div","description",meta[1]));button.append(text,el("span","action","VS Codeで見る"));button.addEventListener("click",()=>open(file,item.line||item.startLine,button));return button;};
  const overview=(data)=>{const root=el("div","list","");if(!data.groups?.length)return el("div","empty","保存済みの概要はありません。生成すると意味ごとのまとまりを表示できます。");data.groups.forEach(group=>{const box=el("section","group","");box.append(el("h3","group-title",group.label||"コードのまとまり"));const items=el("div","group-items","");(group.items||[]).forEach(item=>{const kind=item.kind==="class"?"クラス":item.kind==="constant"?"定数":"関数";items.append(codeCard(item,data.file,kind+" · "+data.file+":"+item.line));});box.append(items);root.append(box);});if(data.relationships?.length){const box=el("section","relations","");box.append(el("h3","","呼び出し関係"));data.relationships.forEach(edge=>box.append(el("p","relation",edge.from+" → "+edge.to+(edge.line?" · L"+edge.line:""))));root.append(box);}if(data.readingOrder?.length){const box=el("section","reading-order","");box.append(el("h3","","推奨する読む順"));data.readingOrder.forEach((item,index)=>box.append(el("p","order-item",String(index+1)+". "+item.label+" · L"+item.line)));root.append(box);}return root;};
  const project=(data)=>{const root=el("div","list","");const byDir=new Map();(data.files||[]).forEach(file=>{const list=byDir.get(file.directory)||[];list.push(file);byDir.set(file.directory,list);});[...byDir.entries()].sort(([a],[b])=>a.localeCompare(b)).forEach(([directory,files])=>{const box=el("section","group","");const dir=(data.directories||[]).find(value=>value.path===directory);box.append(el("h3","group-title",directory==="."?"プロジェクト直下":directory));if(dir?.description)box.append(el("p","description",dir.description));const items=el("div","group-items","");files.forEach(file=>items.append(codeCard({label:file.path,description:file.description},file.path,"関数: "+(file.functions||[]).join(", ")||"関数なし")));box.append(items);root.append(box);});if((data.imports||[]).length){const box=el("section","imports","");box.append(el("h3","","import 関係"));data.imports.forEach(edge=>box.append(el("p","import",edge.from+" → "+edge.to+(edge.label?" · "+edge.label:""))));root.append(box);}return root;};
  const annotations=(data)=>{if(!data.items?.length)return el("div","empty","保存済みの名称辞書はありません。");const root=el("div","list","");data.items.forEach(item=>{const button=el("button","card warning","");button.type="button";const text=el("div","","");text.append(el("div","name",item.label));text.append(el("div","meta","名称 · "+(item.scope==="range"?"選択範囲":"ファイル全体")));text.append(el("div","description",item.explanation));button.append(text,el("span","annotation-range","L"+item.startLine));button.addEventListener("click",()=>open(sourceFile,item.startLine,button));root.append(button);});return root;};
  const trace=(data)=>{const root=el("div","list","");const names=data.funcNames||[];if(!names.length)return el("div","empty","このファイルには保存済みの実行トレースがありません。");names.forEach(name=>root.append(codeCard({label:name+"()",description:"具体例で実行した値の変化はVS Codeのコード右側に表示しています。"},sourceFile,"実行トレース")));const loops=el("p","role",data.loopCount?"ループ: "+data.loopCount+"個。VS Codeで周回を切り替えられます。":"ループはありません。");root.append(loops);return root;};
  const render=(result)=>{try{const value=result?.result??result;if(value?.isError)throw new Error(value?.content?.find(item=>item?.type==="text")?.text||"表示できませんでした。");const data=value?.structuredContent||{};const meta=value?._meta??value?.meta;workspaceRoot=typeof meta?.guideWorkspaceRoot==="string"?meta.guideWorkspaceRoot:"";sourceFile=typeof data.file==="string"?data.file:"";let kind="",view=null;if(data.overview){kind="概要";view=data.overview;}else if(data.project){kind="構成";view=data.project;}else if(data.annotations){kind="インライン解説";view=data.annotations;}else if(data.trace){kind="実行トレース";view=data.trace;}else throw new Error("表示データを受け取れませんでした。");document.getElementById("eyebrow").textContent=kind;document.getElementById("title").textContent=view.title||view.file||"AI Code Guide";const role=document.getElementById("role");role.textContent=view.role||"";role.hidden=!view.role;const content=document.getElementById("content");content.replaceChildren(kind==="概要"?overview(view):kind==="構成"?project(view):kind==="インライン解説"?annotations(view):trace(view));document.body.classList.remove("error");document.body.classList.add("ready");}catch(error){document.getElementById("status").textContent=error?.message||"表示できませんでした。";document.body.classList.remove("ready");document.body.classList.add("error");}};
  window.addEventListener("message",event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(message.id!==undefined&&pending.has(message.id)){const item=pending.get(message.id);pending.delete(message.id);message.error?item.reject(message.error):item.resolve(message.result);return;}if(message.method==="ui/notifications/tool-result"){const value=message.params?.result??message.params;const data=value?.structuredContent||{};if(data.overview){const state=data.viewState;if(!state||state.viewMode!=="overview"||typeof state.stateReceiptId!=="string"||!state.stateReceiptId){document.getElementById("status").textContent="概要ビューの状態確認を受け取れませんでした。";document.body.classList.add("error");return;}document.getElementById("view-state").textContent="表示: overview · "+state.resourceVersion+" · receipt "+state.stateReceiptId;}render(message.params);}},{passive:true});
  request("ui/initialize",{appInfo:{name:"ai-code-guide-detail",version:"0.2.0"},appCapabilities:{},protocolVersion:"2026-01-26"}).then(()=>notify("ui/notifications/initialized",{})).catch(()=>{document.getElementById("status").textContent="表示を初期化できませんでした。";document.body.classList.add("error");});
</script></body></html>`;
}
